# permissions for end users to view dhcpconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openwrt-controller
    app.kubernetes.io/managed-by: kustomize
  name: dhcpconfig-viewer-role
rules:
- apiGroups:
  - openwrt.daimonaslabs.io
  resources:
  - dhcpconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openwrt.daimonaslabs.io
  resources:
  - dhcpconfigs/status
  verbs:
  - get
