# permissions for end users to view firewallconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openwrt-controller
    app.kubernetes.io/managed-by: kustomize
  name: firewallconfig-viewer-role
rules:
- apiGroups:
  - openwrt.daimonaslabs.io
  resources:
  - firewallconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openwrt.daimonaslabs.io
  resources:
  - firewallconfigs/status
  verbs:
  - get
