---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - openwrt.daimonaslabs.io
  resources:
  - dhcpconfigs
  - firewallconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openwrt.daimonaslabs.io
  resources:
  - dhcpconfigs/finalizers
  - firewallconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - openwrt.daimonaslabs.io
  resources:
  - dhcpconfigs/status
  - firewallconfigs/status
  verbs:
  - get
  - patch
  - update
