# permissions for end users to edit uciconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openwrt-controller
    app.kubernetes.io/managed-by: kustomize
  name: uciconfig-editor-role
rules:
- apiGroups:
  - openwrt.daimonaslabs.io.daimonaslabs.io
  resources:
  - uciconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openwrt.daimonaslabs.io.daimonaslabs.io
  resources:
  - uciconfigs/status
  verbs:
  - get
